services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: treasory
      POSTGRES_USER: treasory_user
      POSTGRES_PASSWORD: treasory_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        DATABASE_URL: "postgresql://treasory_user:treasory_password@postgres:5432/treasory?schema=public"
    environment:
      DATABASE_URL: "postgresql://treasory_user:treasory_password@postgres:5432/treasory?schema=public"
      JWT_SECRET: "development-jwt-secret-change-in-production"
      NODE_ENV: "development"
      PORT: "3001"
      FRONTEND_URL: "http://localhost:5173"
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"        # Vite dev
      - "24678:24678"      # (optionnel) HMR dédié si tu le forces
    depends_on:
      - backend
    environment:
      VITE_API_URL: "http://localhost:3001/api"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: