version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: treasory
      POSTGRES_USER: treasory_user
      POSTGRES_PASSWORD: treasory_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://treasury_user:treasury_password@postgres:5432/treasury"
      JWT_SECRET: "development-jwt-secret-change-in-production"
      NODE_ENV: "development"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: